spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:fraud_db}
    username: ${DB_USER:frauduser}
    password: ${DB_PASSWORD:fraudpass123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      pool-name: AccountsHikariPool
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
      timeout: ${REDIS_TIMEOUT:2000}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:64}
          max-idle: ${REDIS_POOL_MAX_IDLE:16}
          min-idle: ${REDIS_POOL_MIN_IDLE:8}
          max-wait: ${REDIS_POOL_MAX_WAIT:100}
  main:
    web-application-type: servlet
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: INFO
    com.finlab.accounts: ${LOG_LEVEL:DEBUG}
    org.springframework.jdbc: ${JDBC_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
