spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud_db
    username: frauduser
    password: fraudpass123
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: servlet
  sql:
    init:
      mode: never

server:
  port: 8081
